### ISSUE TITLE
Is it possible to add caching?

### ISSUE THREAD

**Issue by clarkewd** [epheph/fec2din#1]
Would it be possible to add local caching, with an adjustable TTL, maybe 30 seconds or so? For me it takes several seconds for `ec2din` request to be processed.

**Comment by epheph** [comment]
That's a good idea, I'll look into it; shouldn't be too hard.

**Comment by clarkewd** [comment]
Maybe it is also worth checking out boto, [as was suggested as a solution to the delay when using fec2din](http://unix.stackexchange.com/questions/38101/does-bash-have-a-built-in-caching-command-available-sort-of-like-mktemp-or-spon)

**Comment by epheph** [comment]
Man, the EC2 CLI tools are so slow! Great suggestion, I switched to python&boto and it SIGNIFICANTLY sped up a full EC2 instance description!

```
$ time fec2din > /dev/null 2>&1  
real    0m1.030s
user    0m0.214s
sys 0m0.045s

$ time ec2din > /dev/null 2>&1  
real    0m6.651s
user    0m10.241s
sys 0m0.443s
```

Wow, 1 second vs 6.6 ! I have about 50 instances.

I figure if it is this fast, a caching mechanism isn't necessary, but let me know if you're still seeing it as slow, depending on your number of instances; it would be pretty easy to add. You'll have to export new variables to make the new version work, though, as boto doesn't support the CERT & KEY authentication method that the EC2 tools require.

**Comment by clarkewd** [comment]
Thanks for implementing this - the difference is remarkable
